name: Test then deploy auth Workflow
on:
  push:
    paths:
      - "auth-service/**"
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: auth-service-command
        run: |
          cd ./auth-service
          npm install
          npm run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: auth-service-command
        run: |
          cd ./auth-service
          npm install
          npm test
  Package:
    runs-on: ubuntu-latest
    needs:
      - Test
      - eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: "Create .env file"
        run: |
          cd auth-service
          touch .env
          echo CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}" >> .env
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          file: api-gateway/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/showsauthservice:latest
  # deploy:
  #     name: Deploy
  #     needs: [ test, package ]
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Set the Kubernetes context
  #         uses: azure/k8s-set-context@v2
  #         with:
  #           method: service-account
  #           k8s-url: https://devops-project-k8s-14b8a194.hcp.westeurope.azmk8s.io:443hamza@hamza-VirtualBox
  #           k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
